-- 코드를 입력하세요
SELECT n.FLAVOR
FROM (SELECT f.FLAVOR, f.TOTAL_ORDER, i.INGREDIENT_TYPE FROM FIRST_HALF f JOIN ICECREAM_INFO i on (f.FLAVOR = i.FLAVOR)) as n
WHERE n.TOTAL_ORDER > 3000 AND n.INGREDIENT_TYPE = 'fruit_based'
ORDER BY n.TOTAL_ORDER DESC;